export const arrFeatures: { [key: string]: string[] } = {
    
 Birdeye:[
    "Appt Reminders",
    "Mass Texting",
    "Real-Time Online Scheduling",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Patient Texting on Mobile",
],

CareCru:[
    "Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Forms PDF Posts in PMS",
],

Cooper_Vision:[
    "Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Eyewear Ready",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Forms PDF Posts in PMS",
    "Text to Pay",
    "2-Way Patient Logs Sync",
],

'4_Patient_Care':[
    "Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Eyewear Ready",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Forms PDF Posts in PMS",
    "Text to Pay",
    "2-Way Patient Logs Sync",
],

Dear_Doc:[
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Digital Forms",
],

Demand_Force:[
    "Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Email Marketing",
"Real-Time Online Scheduling",
"Review Software",
"Digital Forms",
"Forms Integrate with PMS",
"Forms PDF Posts in PMS",
"Text to Pay",
"2-Way Patient Logs Sync",
"Patient Texting on Mobile",
"See Schedule Anytime",
],

Dental_Symphony:[
    "Digital Forms",
"Treatment Plans",
"Text to Pay",
],


Dentrix_Hub:["Digital Forms",
    "Forms Integrate with PMS",
    "2-Way Forms Sync",
    "Forms PDF Posts in PMS",
    "Forms Autofills Allergies",
    "Forms Autofills Medical History",
    "Forms Autofills Medications",],

    Doctible:["Appt Reminders",
"Patient Recall",
"Email Marketing",
"Review Software",
"Filter Out Unhappy Patients",
"Respond to Reviews",
"Digital Forms",],

Enlive_Forms:["Review Software",
    "Digital Forms",
    "Forms Integrate with PMS",],

    Flex_Dental:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Mass Texting",
"ASAP Lists",
"Email Marketing",
"Real-Time Online Scheduling",
"Appts Book Directly into PMS",
"Review Software",
"Digital Forms",
"Forms Integrate with PMS",
"Forms PDF Posts in PMS",
"Treatment Plans",
"Credit Card Terminal",
"Text to Pay",
"Internal Chat",
"Patient Texting on Mobile",
"See Schedule Anytime",
"Mobile Notifications",],

Kasper:["Patient Texting on Mobile",
    "See Schedule Anytime",
    "Mobile Notifications",],

    Legwork:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Mass Texting",
"ASAP Lists",
"Email Marketing",
"Real-Time Online Scheduling",
"Appts Book Directly into PMS",
"Review Software",
"Digital Forms",
"Forms Integrate with PMS",
"Forms PDF Posts in PMS",
"Patient Texting on Mobile",],


Lighthouse_360:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Mass Texting",
    "Reminders in Spanish",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Review Software",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Forms PDF Posts in PMS",
    "Text to Pay",],

    M_Consent:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"ASAP Lists",
"Real-Time Online Scheduling",
"Review Software",
"Digital Forms",
"Forms Integrate with PMS",
"2-Way Forms Sync",
"Treatment Plans",
"Text to Pay",],

    DI_Modento_LocalMed:[
    "Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Mass Texting",
    "Reminders in Spanish",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Dynamic Appt Requests",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Auto-Assign Forms",
    "Incomplete Form Reminders",
    "Forms PDF Posts in PMS",
    "Treatment Plans",
    "Credit Card Terminal",
    "Text to Pay",
    "Payment Plans",
    "In-House Insurance",
    "Payments Post in Ledger",
    "Payment Reminders",
    "2-Way Patient Logs Sync",
    "Internal Chat",
    "Patient Texting on Mobile",
    "Practice Analytics",
    "Daily Huddle",
    "Patient Lists",
    "Follow Ups",
    "Provider-level Metrics",
    "Analytics on Mobile",
    "Unscheduled Family Members",
    "Practice Metrics on the Go",
    "Morning Huddle on the Go",
],

    Modento:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Mass Texting",
"Reminders in Spanish",
"ASAP Lists",
"Email Marketing",
"Real-Time Online Scheduling",
"Appts Book Directly into PMS",
"Dynamic Appt Requests",
"Review Software",
"Filter Out Unhappy Patients",
"Respond to Reviews",
"Digital Forms",
"Forms Integrate with PMS",
"Auto-Assign Forms",
"Incomplete Form Reminders",
"Forms PDF Posts in PMS",
"Treatment Plans",
"Credit Card Terminal",
"Text to Pay",
"Payment Plans",
"In-House Insurance",
"Payments Post in Ledger",
"Payment Reminders",
"2-Way Patient Logs Sync",
"Internal Chat",
"Patient Texting on Mobile",
"Practice Analytics",
"Daily Huddle",
"Patient Lists",
"Follow Ups",
"Provider-level Metrics",
"Analytics on Mobile",
"Unscheduled Family Members",
"Practice Metrics on the Go",
"Morning Huddle on the Go",],

    Nexhealth:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Mass Texting",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Dynamic Appt Requests",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Auto-Assign Forms",
    "Incomplete Form Reminders",
    "Forms PDF Posts in PMS",
    "Credit Card Terminal",
    "Text to Pay",
    "2-Way Patient Logs Sync",
    "Internal Chat",],

    Opera_DDS:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Mass Texting",
"ASAP Lists",
"Review Software",
"Filter Out Unhappy Patients",
"Respond to Reviews",
"Digital Forms",
"Forms Integrate with PMS",
"Auto-Assign Forms",
"Incomplete Form Reminders",
"2-Way Forms Sync",
"Forms PDF Posts in PMS",
"2-Way Patient Logs Sync",
"Internal Chat",],

    Patient_Activator:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Review Software",
    "Filter Out Unhappy Patients",],

    Dentrix_Patient_Engage:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Real-Time Online Scheduling",
"Appts Book Directly into PMS",
"Review Software",
"Filter Out Unhappy Patients",
"Digital Forms",
"Forms Integrate with PMS",],

    Patient_Viewer:["Appt Reminders",
    "Auto Confirmations",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",],

    Patient_Xpress:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Real-Time Online Scheduling",
"Appts Book Directly into PMS",
"Review Software",
"Treatment Plans",
"Credit Card Terminal",
"Text to Pay",],

    Podium:["Mass Texting",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Credit Card Terminal",
    "Text to Pay",
    "Patient Texting on Mobile",
    "Mobile Notifications",
    "Take Payments on Mobile",],

    Practice_By_Numbers:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Email Marketing",
"Real-Time Online Scheduling",
"Appts Book Directly into PMS",
"Review Software",
"Filter Out Unhappy Patients",
"Respond to Reviews",
"Digital Forms",
"Forms Integrate with PMS",
"Forms PDF Posts in PMS",
"Credit Card Terminal",
"Text to Pay",
"Payment Reminders",
"2-Way Patient Logs Sync",
"Internal Chat",
"Patient Texting on Mobile",
"See Schedule Anytime",
"Internal Chat on Mobile",
"Mobile Notifications",
"Practice Analytics",
"Daily Huddle",
"Patient Lists",
"Provider-level Metrics",
"Unscheduled Family Members",
],

    Practice_Mojo:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Email Marketing",
    "Review Software",
    "Filter Out Unhappy Patients",],

    RecallMax:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"ASAP Lists",
"Email Marketing",
"Multi-location Emails",
"Real-Time Online Scheduling",
"Patient Lists"],

    Revenue_Well:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Mass Texting",
    "Reminders in Spanish",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Review Software",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Forms PDF Posts in PMS",
    "Credit Card Terminal",
    "Text to Pay",
    "2-Way Patient Logs Sync",
    "Internal Chat",
    "Patient Texting on Mobile",
    "See Schedule Anytime",
    "Mobile Notifications",
    "VoIP Phones",
    "Integrated Caller ID",
    "Visual Voicemails",
    "1 Main Number",
    "Call Recording",],

    Simplifeye:["Patient Recall",
"Real-Time Online Scheduling",
"Review Software",
"Credit Card Terminal",
"Text to Pay",],

    Solution_Reach:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Forms PDF Posts in PMS",
    "2-Way Patient Logs Sync",
    "Internal Chat",
    "Patient Texting on Mobile",
    "See Schedule Anytime",],

    Swell:["Mass Texting",
"Real-Time Online Scheduling",
"Review Software",
"Filter Out Unhappy Patients",
"Respond to Reviews",],

    Vyne:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Review Software",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Credit Card Terminal",
    "Text to Pay",
    "2-Way Patient Logs Sync",
    "Internal Chat",],

    Weave:["Appt Reminders",
"Auto Confirmations",
"Patient Recall",
"Mass Texting",
"ASAP Lists",
"Email Marketing",
"Real-Time Online Scheduling",
"Review Software",
"Filter Out Unhappy Patients",
"Digital Forms",
"Forms Integrate with PMS",
"Incomplete Form Reminders",
"Forms PDF Posts in PMS",
"Credit Card Terminal",
"Text to Pay",
"Payment Reminders",
"2-Way Patient Logs Sync",
"Internal Chat",
"Desktop Notifications",
"Patient Texting on Mobile",
"See Schedule Anytime",
"Internal Chat on Mobile",
"Mobile Notifications",
"Take Payments on Mobile",
"VoIP Phones",
"Integrated Caller ID",
"Integrated eFax",
"Visual Voicemails",
"Missed Call Text",
"Missed Call Insights",
"1 Main Number",
"Call Recording",
"Easy Call Override",
"Text from Office #",
"All Comms Post to Patient Logs",
"Take Calls on Mobile",
"Check Voicemails and eFaxes",],

    YAPI:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Reminders in Spanish",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Auto-Assign Forms",
    "Incomplete Form Reminders",
    "2-Way Forms Sync",
    "Forms PDF Posts in PMS",
    "2-Way Patient Logs Sync",
    "Internal Chat",],

    ZocDoc:["Real-Time Online Scheduling",
"Appts Book Directly into PMS",],

    AT_T:[],
    Bell:[],
    Comcast:["VoIP Phones",
    "Visual Voicemails",],

    xFinity:["VoIP Phones",
"Visual Voicemails",],

    GoTo_Connect:["VoIP Phones",
    "Softphone (Mobile, Web, Desktop)",
    "Visual Voicemails",
    "Missed Call Insights",
    "Text from Office #",
    "Call Recording",
    "Take Calls on Mobile",
    "Check Voicemails and eFaxes",],

    Intiveo:["VoIP Phones",
"Softphone (Mobile, Web, Desktop)",
"Visual Voicemails",
"Missed Call Insights",
"Text from Office #",
"Take Calls on Mobile",
"Call Recording",
"Check Voicemails and eFaxes",],

    Mango:["VoIP Phones",
    "Integrated Caller ID",
    "Integrated eFax",
    "Visual Voicemails",
    "Missed Call Insights",
    "Call Recording",
    "Easy Call Override",],

    Nextiva:["VoIP Phones",
"Softphone (Mobile, Web, Desktop)",
"Visual Voicemails",
"Missed Call Insights",
"Text from Office #",
"Take Calls on Mobile",
"Call Recording",
"Check Voicemails and eFaxes",],

    Ooma:["VoIP Phones",
    "Softphone (Mobile, Web, Desktop)",
    "Visual Voicemails",
    "Missed Call Insights",
    "Text from Office #",
    "Take Calls on Mobile",
    "Call Recording",
    "Check Voicemails and eFaxes",],

    Optimum:["VoIP Phones",
    "Softphone (Mobile, Web, Desktop)",
    "Visual Voicemails",
    "Missed Call Insights",
    "Text from Office #",
    "Take Calls on Mobile",
    "Call Recording",
    "Check Voicemails and eFaxes",],

    Peer_Logic:["VoIP Phones",
    "Visual Voicemails",
    "Integrated Caller ID",
    "Missed Call Insights",
    "Call Recording",
    ],
    
    RingCentral:["VoIP Phones",
    "Softphone (Mobile, Web, Desktop)",
    "Visual Voicemails",
    "Missed Call Insights",
    "Text from Office #",
    "Take Calls on Mobile",
    "Call Recording",
    "Check Voicemails and eFaxes",],

    Shaw:[],
    
    Spectrum:["VoIP Phones",
"Visual Voicemails",],

    Verizon:["VoIP Phones",
    "Visual Voicemails",],

    _8x8:["VoIP Phones",
    "Softphone (Mobile, Web, Desktop)",
    "Visual Voicemails",
    "Missed Call Insights",
    "Text from Office #",
    "Take Calls on Mobile",
    "Call Recording",
    "Check Voicemails and eFaxes",],
    OTHER:[],
    Dental_Intel:["Appt Reminders",
    "Auto Confirmations",
    "Patient Recall",
    "Mass Texting",
    "Reminders in Spanish",
    "ASAP Lists",
    "Email Marketing",
    "Real-Time Online Scheduling",
    "Appts Book Directly into PMS",
    "Dynamic Appt Requests",
    "Review Software",
    "Filter Out Unhappy Patients",
    "Respond to Reviews",
    "Digital Forms",
    "Forms Integrate with PMS",
    "Auto-Assign Forms",
    "Incomplete Form Reminders",
    "Forms PDF Posts in PMS",
    "Treatment Plans",
    "Credit Card Terminal",
    "Text to Pay",
    "Payment Plans",
    "In-House Insurance",
    "Payments Post in Ledger",
    "Payment Reminders",
    "2-Way Patient Logs Sync",
    "Internal Chat",
    "Patient Texting on Mobile",
    "Practice Analytics",
    "Daily Huddle",
    "Patient Lists",
    "Follow Ups",
    "Provider-level Metrics",
    "Analytics on Mobile",
    "Unscheduled Family Members",
    "Practice Metrics on the Go",
    "Morning Huddle on the Go",],

    Jarvis:["Practice Analytics",
"Daily Huddle",
"Patient Lists",
"Provider-level Metrics",
"Multi-location Roll Up Views",
"Unscheduled Family Members",],
    EHR_PMS:[],

   
}
export const verificationArrFeatures:{[key:string]:string[]}={
    Zuub:["Full Insurance Portal Verification",],
    AirPay:["Full Insurance Portal Verification",],
    E_Assist:["Full Insurance Portal Verification",],
    Vyne:["Eligilibility PDF Attached to Patient File",],
    Weave:["Eligilibility PDF Attached to Patient File",],
}