 export const  communicationsList: { text: string; value: boolean; toolTip:string }[] = [
    { text: 'VoIP Phones', value: true, toolTip:'Clear, reliable, digital calling that centralizes all your communication.' },
    { text: 'Softphone (Mobile, Web, Desktop)', value: true, toolTip:'Flexible calling options across all of your devices. Work away from the phone and still be able to take any calls needed.' },
    { text: 'Integrated Caller ID', value: true, toolTip:'Know who is calling your office and view basic patient details before you answer the call.' },
    { text: 'Integrated eFax', value: true, toolTip:'Paperless faxing? Yep! This feature uses your email to send and receive faxes' },
    { text: 'Visual Voicemails', value: true, toolTip:'Easily manage voicemails through visual cues.' },
    { text: 'Missed Call Text', value: true, toolTip:'Automatically send text messages to your patients on busy days, after hours, or whenever you miss their calls.' },
    { text: 'Missed Call Insights', value: true, toolTip:'Get relevant data about what took place when someone called your office.' },
    { text: '1 Main Number', value: true, toolTip:'Simplify communication by using a single phone number for all patient correspondence.' },
    { text: 'Call Recording', value: true, toolTip:'Record calls for future reference, quality assurance, and training opportunities.' },
    { text: 'Easy Call Override', value: true, toolTip:'Create a temporary call flow without having to modify your normal flow. Great for holidays or unexpected office closures.' },
    { text: 'Text from Office #', value: true, toolTip:'When you text your patients, your office number will appear so they are more likely to respond or take a requested action.' },
    { text: 'All Comms Post to Patient Logs', value: true, toolTip:'Everything you do, say, and document about a patient in Adit will automatically sync to its respective patient file in your PMS.' },
  ];

   export const operations: { text: string; value: boolean; toolTip:string }[] = [
    { text: 'Appt Reminders', value: true, toolTip:'Send appointment reminders via text or email to reduce the number of no-shows and last-minute cancellations.' },
    { text: 'Auto Confirmations', value: true, toolTip:'When a patient books an appointment, they will receive an automatic text/email assuring them that their appointment is booked.' },
    { text: 'Patient Recall', value: true, toolTip:'Help unscheduled patients book their re-care appointments by sending automated messages.' },
    { text: 'Mass Texting', value: true, toolTip:'Deliver personalized text messages to a specific group of patients all at once.' },
    { text: 'Reminders in Spanish', value: true, toolTip:'Translate your automated reminders into Spanish for patients who have Spanish set as their prefered language in your PMS.' },
    { text: 'ASAP Lists', value: true, toolTip:'Create a list of patients you can contact to fill in any open slots in your schedule after a last-minute cancellation or rescheduling.' },
    { text: 'Eyewear Ready', value: true, toolTip:'' },
    { text: 'Email Marketing', value: true, toolTip:'Create beautifully branded emails and send them to segment patient lists to keep your patients engaged.' },
    { text: 'Drip Campaigns', value: true, toolTip:'Send several emails to patients and segmented audiences over timed intervals.' },
    { text: 'Multi-location Emails', value: true, toolTip:'Easily send emails to patient segments across different locations.' },
    { text: 'Real-Time Online Scheduling', value: true, toolTip:'Allow your patients to book specific services at specific times 24/7, even when your office is closed.' },
    { text: 'Appts Book Directly into PMS', value: true, toolTip:"Adit syncs all appointment bookings to your PMS so there's no confusion about appointment details." },
    { text: 'Dynamic Appt Requests', value: true, toolTip:'Pre-populate specific details in requests such as appointment type, and providers available. So when a patient books their appointment, they will only have to select the date and time.' },
    { text: 'Bulk Appt Requests', value: true, toolTip:'Send personalized appointment requests via email or text to a specific group of patients all at one time.' },
    { text: 'Review Software', value: true, toolTip:'Send a text message with a link to your preferred review site to make it easy for patients to leave reviews.' },
    { text: 'Filter Out Unhappy Patients', value: true, toolTip:'Redirect patients leaving negative reviews to your office rather than your business pages.' },
    { text: 'Respond to Reviews', value: true, toolTip:"View and respond to your patient's reviews directly in Adit without logging into a review site." },
    { text: 'Digital Forms', value: true, toolTip:'Eliminate tedious, repetitive data entry tasks by sending patients digital forms via text/email to complete at home before their appointment.' },
    { text: 'Forms Integrate with PMS', value: true, toolTip:'Fields from digital forms map over to your PMS so when patients complete forms, the information is automatically updated in your PMS.' },
    { text: 'Auto-Assign Forms', value: true, toolTip:'Automatically send digital forms to your patients based on specific criteria like patient type, appointment type, and treatment code.' },
    { text: 'Incomplete Form Reminders', value: true, toolTip:'Send reminder messages to patients that are missing information from their digital forms.' },
    { text: '2-Way Forms Sync', value: true, toolTip:'Adit syncs all digital form fields to your PMS so you can view form data from Adit without opening your PMS and visa versa.' },
    { text: 'Forms PDF Posts in PMS', value: true, toolTip:'Upload PDF forms and update information directly into your PMS from Adit.' },
    { text: 'Forms Autofills Allergies', value: true, toolTip:'Adit pulls allergy records from your PMS so that when a patient fills out a form, allergy information auto-populates.' },
    { text: 'Forms Autofills Medical History', value: true, toolTip:'When you patient fills out a digital form, the form auto-populates information based on data from your PMS.' },
    { text: 'Forms Autofills Medications', value: true, toolTip:'Adit pulls medication records from your PMS so that when a patient is filling out a form, their medications auto populate.' },
    { text: 'Treatment Plans', value: true, toolTip:'Build fully customizable digital treatment plans for your patients to complete in the office or at home. Add different plan and payment options, customize pricing and discounts, and send digital consent forms all from one place.' },
    { text: 'All-In-One Tx Acceptance', value: true, toolTip:'Easily create and send treatment plans to patients and capture approval, signature, and payment all in one place.' },
    { text: 'Credit Card Terminal', value: true, toolTip:'This piece of hardware allows your team to process credit card payments in the office via swipe or tap.' },
    { text: 'Text to Pay', value: true, toolTip:'Send patients a secured link via text message to allow them to pay for treatments anytime, anywhere.' },
    { text: 'Payment Plans', value: true, toolTip:'Allow patients to pay off a balance over a period of installments using a card saved on file.' },
    { text: 'In-House Insurance', value: true, toolTip:'Set up in-house payment and insurance plans to boost treatment acceptance and give patients flexible payment options.' },
    { text: 'Payments Post in Ledger', value: true, toolTip:'Easily log all patient payment activity directly into your ledger in your PMS.' },
    { text: 'Payment Reminders', value: true, toolTip:'Let patients know they have an outstanding balance on their account and allow them to pay online through a secured link.' },
    { text: '2-Way Patient Logs Sync', value: true, toolTip:'Adit logs all patient communication into their respective PMS profile so you can view everything from Adit without opening your PMS.' },
    { text: 'Internal Chat', value: true, toolTip:'No more long email chain messages or third-party chat software. Now, your team can send secured messages, create group chats, send media files, and more in Adit!' },
    { text: 'Desktop Notifications', value: true, toolTip:'Get instant notifications when patients take any action like calling in, texting, faxing, completing forms, making payments, etc.' },
  ];

   export const  analytics: { text: string; value: boolean; toolTip:string }[] = [
    { text: 'Practice Analytics', value: true, toolTip:'Adit puts the right metrics in front of your staff with dental clinic analytics to empower them to make the best real-time decisions for your practice.' },
    { text: 'Daily Huddle', value: true, toolTip:'Real-time snapshots of the main areas of your practice that influence performance like appointments, new patients, production, etc.' },
    { text: 'Patient Lists', value: true, toolTip:"Build lists of patients with specific details in common, like 'unscheduled treatments in the last 365 days,' then use them to make decisions or take action." },
    { text: 'Bulk Requests', value: true, toolTip:'Text multiple patients at once to request appointments, reviews, form completion and more.' },
    { text: 'Follow Ups', value: true, toolTip:'Customize and automate your Follow-up tasks to help your team stay on track with the most important tasks and not duplicate work.' },
    { text: 'Provider-level Metrics', value: true, toolTip:"Track each provider's production per visit/hour/day/week to see if they are meeting their performance goals." },
    { text: 'Operatory-level Metrics', value: true, toolTip:'See which operatories are in use or open as well as the number of times utilized in each operatory. Plus, view potential lost revenue and opportunities to maximize revenue by operatory.' },
    { text: 'Multi-location Roll Up Views', value: true, toolTip:'See data across multiple locations and how your group of practices are doing as whole.' },
    { text: 'Analytics on Mobile', value: true, toolTip:'View and manage anyaltics data from your mobile device.' },
    { text: 'Data Refreshes Every 5 Mins', value: true, toolTip:'All the data Adit is capturing in Practice Analytics updates every 5 minutes so you have the most accurate information at all times.' },
    { text: 'Multi-Year Growth Dashboards', value: true, toolTip:'View year-over-year production and growth metrics and gain insights on which areas need improvement.' },
    { text: 'Patient Churn Reports', value: true, toolTip:'View which patients have been inactive for an extended period of time.' },
    { text: 'Patient Lifetime Value', value: true, toolTip:'Calculate the monetary value each patient brings to your practice over a lifetime to make better decisions about the time and resources you are willing to use to retain them.' },
    { text: 'Unscheduled Family Members', value: true, toolTip:'View which patients have family members who have not yet scheduled appointments with your practice.' },
    { text: 'Collections Dashboards', value: true, toolTip:'Track accounts receivable numbers and manage all collections and claims across your practice.' },
  ];
   export const  mobile: { text: string; value: boolean; toolTip:string }[] = [
    { text: 'Take Calls on Mobile', value: true, toolTip:'Make and receive calls from your cell phone as if you were in the office.' },
    { text: 'Check Voicemails and eFaxes', value: true, toolTip:'Listen to and view all voicemails and faxes from your mobile device on the go.' },
    { text: 'IP Address & Geo Restrictions', value: true, toolTip:'Restrict access to your staff based on location, thereby restricting access to patient data only when your staff is at the practice.' },
    { text: 'Patient Texting on Mobile', value: true, toolTip:'Communicate with your patients from your cell phone.' },
    { text: 'See Schedule Anytime', value: true, toolTip:"Finally, you don't have to be in the office to view your schedule! Check and manage your schedule from your cell phone anytime, anywhere." },
    { text: 'Internal Chat on Mobile', value: true, toolTip:"Chat with your team on the go whether it's with one location or with multiple." },
    { text: 'Mobile Notifications', value: true, toolTip:"Push notifications to your mobile device so you know what's happening even when you're not in the office." },
    { text: 'Take Payments on Mobile', value: true, toolTip:'' },
    { text: 'Request Review on Mobile', value: true, toolTip:'Send a review request directly from a mobile device.' },
    { text: 'Request Appts, Forms, Reviews', value: true, toolTip:'Send appointment, form, and review requests from your mobile device.' },
    { text: 'Practice Metrics on the Go', value: true, toolTip:'View all your vital practice metrics from your mobile device.' },
    { text: 'Morning Huddle on the Go', value: true, toolTip:'View your Morning Huddle metrics on any mobile device. Perfect for team members working remotely or for meetings in rooms without computers.' },
  ];
   export const verifications: { text: string; value: boolean; toolTip:string }[] = [
    { text: 'Full Insurance Portal Verification', value: true, toolTip:'' },
    { text: 'Eligilibility PDF Attached to Patient File', value: true, toolTip:'' },
    { text: 'Automate Eligilibty Summary to Patients Notes', value: true, toolTip:'' },
    { text: 'Customize Treatment Codes', value: true, toolTip:'' },
    { text: 'Customize Frequency of Verification', value: true, toolTip:'' },
    { text: 'Automate Insurance Requests to Patients', value: true, toolTip:'' },
  ];

   