export interface Dashboard {
    id: number;
    agreement_id: string;
    crm_agreement_id: string | null;
    crm_reseller_request_id: string | null;
    organization_id: string | null;
    organization_name: string | null;
    org_poc_name: string | null;
    org_poc_email: string | null;
    org_poc_work_number: string | null;
    org_poc_cell_number: string | null;
    deal_id: string | null;
    deal_name: string | null;
    user_id: number;
    user_type: string;
    currency_type: string | null;
    practice_industry: string | null;
    reseller_agreement_type: string | null;
    sales_person_name: string;
    sales_person_email: string;
    sales_person_verify_code: string;
    resellr_practice_name: string | null;
    resellr_contact_email: string | null;
    resellr_practice_address1: string | null;
    resellr_practice_address2: string | null;
    resellr_city: string | null;
    resellr_state: string | null;
    resellr_office_phone: string | null;
    resellr_office_website: string | null;
    resellr_promotion_type: string;
    resellr_rate: string | null;
    multi_locations: string;
    sales_person_client: string;
    sales_person_account_id: string;
    schedule_by: string | null;
    sales_person_account_name: string;
    sales_person_promotion_type: string;
    sales_person_promotion_expiry_date: string | null;
    monthly_orginal_tech_bundle_price: string;
    monthly_discnt_tech_bundle_price: string;
    monthly_orginal_analytic_bundle_price: string;
    monthly_discnt_analytic_bundle_price: string;
    monthly_orginal_aditlite_bundle_price: string | null;
    monthly_discnt_aditlite_bundle_price: string | null;
    annual_orginal_tech_bundle_price: string;
    annual_discnt_tech_bundle_price: string;
    annual_orginal_analytic_bundle_price: string;
    annual_discnt_analytic_bundle_price: string;
    annual_orginal_aditlite_bundle_price: string | null;
    annual_discnt_aditlite_bundle_price: string | null;
    activation_fee: string;
    hardware_credit_monthly: string;
    hardware_credit_annually: string;
    status: string;
    crm_attachement_sync: string | null;
    au_promo_check: string | null;
    display_pricing: string;
    display_techstack: string;
    tech_package_only: string | null;
    practice_ehr: string | null;
    other_ehr: string | null;
    first_open: string | null;
    last_open: string | null;
    open_count: string | null;
    current_step: string | null;
    user_created: string | null;
    note_for_reseller: string | null;
    user_approved: string | null;
    sync_with_adit_app: number;
    step_4_completed: number;
    opted_in: number;
    booked: number;
    i_accept_hardware: number;
    signature_url: string | null;
    signatory_name: string | null;
    exist_signup_link: string | null;
    created_at: string;
    updated_at: string;
  }
  