export const mockData = {
  users: [
    {
      id: 1,
      name: 'admin',
      username: 'admin',
      email: 'admin@example.com',
      password: 'admin123', // In real app, this would be hashed
      role: 'admin',
      status: 'active',
      permissions: [
        'view_users',
        'add_users',
        'edit_users',
        'delete_users',
        'view_roles',
        'add_roles',
        'edit_roles',
        'delete_roles',
        'view_agreements',
        'add_agreements',
        'edit_agreements',
        'delete_agreements',
        'view_settings',
        'view_permission',
        'edit_permissions',
        'delete_permission',
        'add_permissions',
        'add_admin',
        'assign_permissions',
      ],
    },
    {
      id: 2,
      username: 'user',
      email: 'user@example.com',
      password: 'user123',
      role: 'user',
      status: 'active',
      permissions: ['view_agreements', 'add_agreements'],
    },
    {
      id: 3,
      username: 'manager',
      email: 'manager@example.com',
      password: 'manager123',
      role: 'manager',
      status: 'active',
      permissions: [
        'view_users',
        'view_agreements',
        'edit_agreements',
        'view_roles',
      ],
    },
  ],
  roles: [
    {
      id: 1,
      name: 'admin',
      description: 'Administrator with full access',
    },
    {
      id: 2,
      name: 'user',
      description: 'Regular user with limited access',
    },
    {
      id: 3,
      name: 'manager',
      description: 'Manager with elevated access',
    },
  ],
  permissions: [
    {
      id: 1,
      name: 'view_users',
      description: 'Can view users',
    },
    {
      id: 2,
      name: 'add_users',
      description: 'Can add new users',
    },
    {
      id: 3,
      name: 'edit_users',
      description: 'Can edit users',
    },
    {
      id: 4,
      name: 'delete_users',
      description: 'Can delete users',
    },
    {
      id: 5,
      name: 'view_roles',
      description: 'Can view roles',
    },
    {
      id: 6,
      name: 'add_roles',
      description: 'Can add new roles',
    },
    {
      id: 7,
      name: 'edit_roles',
      description: 'Can edit roles',
    },
    {
      id: 8,
      name: 'delete_roles',
      description: 'Can delete roles',
    },
    {
      id: 9,
      name: 'view_agreements',
      description: 'Can view agreements',
    },
    {
      id: 10,
      name: 'add_agreements',
      description: 'Can add new agreements',
    },
    {
      id: 11,
      name: 'edit_agreements',
      description: 'Can edit agreements',
    },
    {
      id: 12,
      name: 'delete_agreements',
      description: 'Can delete agreements',
    },
    {
      id: 13,
      name: 'view_settings',
      description: 'Can view settings',
    },
    {
      id: 14,
      name: 'view_permission',
      description: 'Can view permissions',
    },
    {
      id: 15,
      name: 'edit_permissions',
      description: 'Can edit permissions',
    },
    {
      id: 16,
      name: 'delete_permission',
      description: 'Can delete permissions',
    },
    {
      id: 17,
      name: 'add_permissions',
      description: 'Can add new permissions',
    },
    {
      id: 18,
      name: 'add_admin',
      description: 'Can add new administrators',
    },
    {
      id: 19,
      name: 'assign_permissions',
      description: 'Can assign permissions to roles',
    }
  ],
  systemSettings: {
    theme: 'light',
    language: 'en',
    notifications: true,
    maintenanceMode: false,
  },
  events: [
    {
      id: 1,
      type: 'user_login',
      timestamp: '2024-03-20T10:00:00Z',
      userId: 1,
      details: 'User logged in successfully',
    },
    {
      id: 2,
      type: 'agreement_created',
      timestamp: '2024-03-20T11:00:00Z',
      userId: 2,
      details: 'New agreement created',
    },
  ],
  agreements: [
    {
      id: '1',
      companyName: 'Tech Solutions Inc.',
      agreementNumber: 'AG-2024-001',
      status: 'active',
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      type: 'Standard',
      value: 50000,
      contactPerson: 'John Smith',
      email: 'john.smith@techsolutions.com',
      phone: '+1-555-0123',
      multipleLocations: false,
      organization: {
        name: 'Tech Solutions Inc.',
        pocName: 'John Smith',
        pocEmail: 'john.smith@techsolutions.com',
        pocWorkNumber: '+1-555-0123',
        pocCellNumber: '+1-555-0124',
      },
      locations: [
        {
          id: 'loc1',
          name: 'Main Office',
          address: '123 Tech Street',
          city: 'San Francisco',
          state: 'CA',
          postalCode: '94105',
          country: 'United States',
          hardware: {
            phones: [
              { type: 'GRP 2616', count: 2, price: 150 },
              { type: 'GRP 2613', count: 1, price: 100 },
            ],
            terminals: [{ type: 'BBPOS WisePOS E', count: 1, price: 250 }],
          },
          package: {
            name: 'Tech Bundle',
            type: 'annually',
            price: 5000,
            addons: {
              phone: true,
              analytics: true,
              verification: false,
            },
          },
        },
      ],
      packageAndPricing: {
        selectedPackage: 'Tech Bundle',
        billingCycle: 'annually',
        basePrice: 5000,
        addons: {
          phone: 1000,
          analytics: 2000,
          verification: 1500,
        },
        totalPrice: 9500,
      },
      hardware: {
        phones: [
          { type: 'GRP 2616', count: 2, price: 150 },
          { type: 'GRP 2613', count: 1, price: 100 },
        ],
        terminals: [{ type: 'BBPOS WisePOS E', count: 1, price: 250 }],
        totalPrice: 650,
      },
      terms: {
        accepted: true,
        ehrAccepted: true,
        signature: {
          name: 'John Smith',
          date: '2024-01-01',
          url: 'mock-signature-url-1',
        },
      },
    },
    {
      id: '2',
      companyName: 'Global Innovations Ltd',
      agreementNumber: 'AG-2024-002',
      status: 'pending',
      startDate: '2024-02-01',
      endDate: '2025-01-31',
      type: 'Premium',
      value: 75000,
      contactPerson: 'Sarah Johnson',
      email: 'sarah.j@globalinnovations.com',
      phone: '+1-555-0124',
      multipleLocations: true,
      organization: {
        name: 'Global Innovations Ltd',
        pocName: 'Sarah Johnson',
        pocEmail: 'sarah.j@globalinnovations.com',
        pocWorkNumber: '+1-555-0124',
        pocCellNumber: '+1-555-0125',
      },
      locations: [
        {
          id: 'loc1',
          name: 'Headquarters',
          address: '456 Innovation Drive',
          city: 'New York',
          state: 'NY',
          postalCode: '10001',
          country: 'United States',
          hardware: {
            phones: [
              { type: 'GRP 2616', count: 3, price: 150 },
              { type: 'GRP 2613', count: 2, price: 100 },
            ],
            terminals: [
              { type: 'BBPOS WisePOS E', count: 2, price: 250 },
              { type: 'BBPOS WisePOS E Dock', count: 1, price: 49 },
            ],
          },
          package: {
            name: 'Analytic Bundle',
            type: 'monthly',
            price: 7500,
            addons: {
              phone: true,
              analytics: true,
              verification: true,
            },
          },
        },
      ],
      packageAndPricing: {
        selectedPackage: 'Analytic Bundle',
        billingCycle: 'monthly',
        basePrice: 7500,
        addons: {
          phone: 1500,
          analytics: 3000,
          verification: 2000,
        },
        totalPrice: 14000,
      },
      hardware: {
        phones: [
          { type: 'GRP 2616', count: 3, price: 150 },
          { type: 'GRP 2613', count: 2, price: 100 },
        ],
        terminals: [
          { type: 'BBPOS WisePOS E', count: 2, price: 250 },
          { type: 'BBPOS WisePOS E Dock', count: 1, price: 49 },
        ],
        totalPrice: 1049,
      },
      terms: {
        accepted: false,
        ehrAccepted: false,
        signature: {
          name: 'Sarah Johnson',
          date: '2024-02-01',
          url: 'mock-signature-url-2',
        },
      },
    },
    {
      id: '3',
      companyName: 'Digital Dynamics',
      agreementNumber: 'AG-2024-003',
      status: 'expired',
      startDate: '2023-06-01',
      endDate: '2024-05-31',
      type: 'Basic',
      value: 30000,
      contactPerson: 'Mike Brown',
      email: 'mike.b@digitaldynamics.com',
      phone: '+1-555-0125',
      multipleLocations: false,
    },
    {
      id: '4',
      companyName: 'Future Systems Corp',
      agreementNumber: 'AG-2024-004',
      status: 'active',
      startDate: '2024-03-01',
      endDate: '2025-02-28',
      type: 'Enterprise',
      value: 100000,
      contactPerson: 'Lisa Chen',
      email: 'lisa.c@futuresystems.com',
      phone: '+1-555-0126',
      multipleLocations: true,
    },
    {
      id: '5',
      companyName: 'Smart Solutions',
      agreementNumber: 'AG-2024-005',
      status: 'pending',
      startDate: '2024-04-01',
      endDate: '2025-03-31',
      type: 'Standard',
      value: 45000,
      contactPerson: 'David Wilson',
      email: 'david.w@smartsolutions.com',
      phone: '+1-555-0127',
      multipleLocations: false,
    },
  ],
  buttonStates: {
    save: {
      enabled: true,
      loading: false,
      text: 'Save',
    },
    edit: {
      enabled: true,
      loading: false,
      text: 'Edit',
    },
    next: {
      enabled: true,
      loading: false,
      text: 'Next',
    },
    addLocation: {
      enabled: true,
      loading: false,
      text: 'Add Location',
    },
    expand: {
      enabled: true,
      loading: false,
      text: 'Expand',
    },
    collapse: {
      enabled: true,
      loading: false,
      text: 'Collapse',
    },
    copy: {
      enabled: true,
      loading: false,
      text: 'Copy',
    },
    increment: {
      enabled: true,
      loading: false,
      text: '+',
    },
    decrement: {
      enabled: true,
      loading: false,
      text: '-',
    },
    toggle: {
      annually: {
        enabled: true,
        active: true,
        text: 'Annually',
      },
      monthly: {
        enabled: true,
        active: false,
        text: 'Monthly',
      },
    },
  },
  eventReps: [
    {
      id: 1,
      userId: 1,
      name: 'John Smith',
      email: 'john.smith@example.com',
      role: 'Event Rep',
      status: 'active'
    },
    {
      id: 2,
      userId: 2,
      name: 'Sarah Johnson',
      email: 'sarah.j@example.com',
      role: 'Event Rep',
      status: 'active'
    }
  ],
  viewAgreementData: {
    success: true,
    data: {
      id: 41,
      agreementId: "agree33a2dccfddad4a18",
      practiceIndustry: "dental",
      newOrExistingClient: "new",
      multipleLocations: "no",
      fileUpload: null,
      accountId: "1607362001002093045",
      deal: "Chiro",
      deal_id: "1607362001023589001",
      currency: "USD",
      pms: "Dentrix",
      displayPricing: true,
      displayTechStackComparison: false,
      sales_person_promotion_type: "Event",
      event_type: "",
      activation_fee: "0.00",
      analyticAnnual: "649.00",
      techMonthly_Disc: "299.00",
      analyticAnnual_Disc: "399.00",
      techAnnual: "549.00",
      techMonthly: "599.00",
      techAnnual_Disc: "299.00",
      analyticMonthly: "699.00",
      analyticMonthly_Disc: "399.00",
      aditLiteMontly: null,
      aditLiteMontly_Disc: null,
      aditLiteAnnual: null,
      aditLiteAnnual_Disc: null,
      techStackId: null,
      userId: 6,
      aditCore_monthly: null,
      aditCore_annually: null,
      add_on_phones: 100,
      add_on_analytic: 100,
      add_on_verification: 100,
      pozative_Only_Monthly: null,
      pozative_Only_Annually: null,
      verifications_Only_Monthly: null,
      verifications_Only_Annually: null,
      hardwareCreditAnnually: "750.00",
      hardwareCreditMonthly: "300.00",
      promotionExpiryDate_display: "",
      promotionExpiryDate: null,
      status: "Open",
      signature_url: null,
      signatory_name: "sign anme",
      selectPhone: true,
      selectTerminal: false,
      isAnnually: "Annually",
      addOnAditCoreAnalytics: null,
      addOnAditCoreVerification: null,
      addOnPhone: null,
      organization_name: null,
      organization_poc_name: null,
      organization_poc_email: null,
      organization_poc_work_number: null,
      organization_poc_cell_number: null,
      sales_person_name: "vikrant",
      sales_person_email: "test@admin.com",
      no_of_days: 13,
      created_at: "2025-06-12T13:25:32.000Z",
      updated_at: "2025-06-12T14:18:48.000Z",
      User: {
        id: 6,
        name: "vikrant",
        email: "test@admin.com"
      },
      techStack: [
        {
          "id": 11,
          "agreementId": 29,
          "current_phone_provider": "Revenue Well",
          "patient_texting": "Enlive Forms",
          "reminder_recall": "Enlive Forms",
          "digital_forms": null,
          "treatment_presentation_payment_plans": null,
          "current_payment_provider": null,
          "review": null,
          "online_scheduling": null,
          "mass_texting": null,
          "mass_emailing": null,
          "analytics_morning_huddle": null,
          "verification_provider": null,
          "current_phone_provider_price": "500.00",
          "patient_texting_price": "300.00",
          "reminder_recall_price": null,
          "digital_forms_price": null,
          "treatment_presentation_payment_plans_price": null,
          "current_payment_provider_price": null,
          "review_price": null,
          "online_scheduling_price": null,
          "mass_texting_price": null,
          "mass_emailing_price": null,
          "analytics_morning_huddle_price": null,
          "verification_provider_price": null,
          "tech_stack_total_prices": "800.00",
          "features": "[\"Review Software\",\"Digital Forms\",\"Forms Integrate with PMS\",\"Review Software\",\"Digital Forms\",\"Forms Integrate with PMS\"]",
          "created_at": "2025-05-27T16:08:48.000Z",
          "updated_at": "2025-05-28T21:08:27.000Z"
      }
      ],
      practiceData: [
        {
          id: 71,
          agreementId: "agree33a2dccfddad4a18",
          locationId: "4df230cf-818a-4aef-81a9-47b71a175f38",
          practiceName: "practice name",
          locationName: "locatiuobn",
          practiceAdressLine1: "asdasd",
          practiceAdressLine2: "asdasd",
          practiceCity: "asdasd",
          practiceState: "Arkansas",
          practicePostalZipCode: "asdasd2342",
          practiceCountry: "UnitedStates",
          practiceTimezone: "(UTC-7:00) Yukon",
          practiceOfficePhone: "(432) 111-1555",
          practiceEmail: "asd",
          practiceWebsiteUrl: "asd",
          practicePoc: "fds",
          practicePocEmail: "sdf",
          practicePocWorkNumber: "(235) 235-2352",
          practicePocCellNumber: "(235) 213-5235",
          practice_management_software: "AbelDent",
          selectedPackageName: "tech",
          createdAt: "2025-06-12T14:18:48.000Z",
          updatedAt: "2025-06-12T14:18:48.000Z"
        }
      ],
      hardwareOrders: [
        {
          id: "51b8a137-9180-45fa-b78d-1b8d989987f3",
          hardwareName: "Grandstream GRP 2613",
          count: 1,
          locationName: "locatiuobn"
        },
        {
          id: "a54f7d31-3606-4a2c-b072-7894eadba819",
          hardwareName: "GRP 2613 Wall Mount",
          count: 2,
          locationName: "locatiuobn"
        },
        {
          id: "f15148ef-98ab-42f8-ad94-05fe2843546f",
          hardwareName: "Grandstream GRP 2616",
          count: 5,
          locationName: "locatiuobn"
        }
      ],
      fileData: null,
      shippingAddresses: [],
      priceAddons: {
        phone_show: "No",
        phone_orginal_price: null,
        phone_discnt_price: null,
        analytics_show: "No",
        analytics_orginal_price: null,
        analytics_discnt_price: null,
        verification_show: "No",
        verification_orginal_price: null,
        verification_discnt_price: null,
        allow_adit_core_only: 0
      }
    }
  }
};
