export const promotionPricing = {
    'Smile Source': {
      techMonthly: 599,
      techMonthly_Disc: 349,
      techAnnual: 549,
      techAnnual_Disc: 289,
      analyticMonthly: 699,
      analyticMonthly_Disc: 449,
      analyticAnnual: 649,
      analyticAnnual_Disc: 379,
      activation_fee: 0,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
    TruBlu: {
      techMonthly: 599,
      techMonthly_Disc: 299,
      techAnnual: 549,
      techAnnual_Disc: 289,
      analyticMonthly: 699,
      analyticMonthly_Disc: 399,
      analyticAnnual: 649,
      analyticAnnual_Disc: 379,
      activation_fee: 0,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
    DDSOM: {
      techMonthly: 599,
      techMonthly_Disc: 299,
      techAnnual: 549,
      techAnnual_Disc: 299,
      analyticMonthly: 699,
      analyticMonthly_Disc: 399,
      analyticAnnual: 649,
      analyticAnnual_Disc: 379,
      activation_fee: 0,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
    'AIDA Member': {
      techMonthly: 599,
      techMonthly_Disc: 299,
      techAnnual: 549,
      techAnnual_Disc: 299,
      analyticMonthly: 699,
      analyticMonthly_Disc: 399,
      analyticAnnual: 649,
      analyticAnnual_Disc: 399,
      activation_fee: 0,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
    Custom: {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:349,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:299,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,

      activation_fee: 500,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
    Event: {
      // techMonthly: 599,
      // techMonthly_Disc: 449,
      // techMonthly_Disc_Min:349,
      // techMonthly_Disc_Max:449,

      // techAnnual: 549,
      // techAnnual_Disc: 399,
      // techAnnual_Disc_Min:299,
      // techAnnual_Disc_Max:399,

      // analyticMonthly: 699,
      // analyticMonthly_Disc: 549,
      // analyticMonthly_Disc_Max:549,
      // analyticMonthly_Disc_Min:449,

      // analyticAnnual: 649,
      // analyticAnnual_Disc: 499,
      // analyticAnnual_Disc_Max:499,
      // analyticAnnual_Disc_Min:399,

      aditCore_monthly:299,
      aditCore_annually:249,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:150,
      activation_fee: 500,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
    'Outbound AE': {
      techMonthly: 599,
      techMonthly_Disc: 399,
      techMonthly_Disc_Min:349,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 349,
      techAnnual_Disc_Min:299,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 499,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 449,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,      
      activation_fee: 500,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:500
    },
    'Outbound AE (Lite)': {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:249,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:199,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,   
      
      aditLiteMontly:499,
      aditLiteMontly_Disc: 349,
      aditLiteMontly_Disc_Max:349,
      aditLiteMontly_Disc_Min:249,   

      aditLiteAnnual:449,
      aditLiteAnnual_Disc: 299,
      aditLiteAnnual_Disc_Max:299,
      aditLiteAnnual_Disc_Min:199,   

      activation_fee: 500,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:500,
      hardwareCreditAditLiteAnnually: 0,
      hardwareCreditAditLiteMonthly:0
    },
    'Outbound AE (Only Lite)': {
      aditLiteMontly:499,
      aditLiteMontly_Disc: 349,
      aditLiteMontly_Disc_Max:349,
      aditLiteMontly_Disc_Min:249,   

      aditLiteAnnual:449,
      aditLiteAnnual_Disc: 299,
      aditLiteAnnual_Disc_Max:299,
      aditLiteAnnual_Disc_Min:199,   

      activation_fee: 500,
      hardwareCreditAditLiteAnnually: 0,
      hardwareCreditAditLiteMonthly:0
    },
    'Only Lite - 1st Yr Promo': {
      aditLiteMontly:499,
      aditLiteMontly_Disc: 349,
      aditLiteMontly_Disc_Max:349,
      aditLiteMontly_Disc_Min:249,   

      aditLiteAnnual:449,
      aditLiteAnnual_Disc: 299,
      aditLiteAnnual_Disc_Max:299,
      aditLiteAnnual_Disc_Min:199,   

      activation_fee: 500,
      hardwareCreditAditLiteAnnually: 0,
      hardwareCreditAditLiteMonthly:0
    },
    Admin: {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:0,
      techMonthly_Disc_Max:999,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:0,
      techAnnual_Disc_Max:999,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:0,
      analyticMonthly_Disc_Min:999,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:0,
      analyticAnnual_Disc_Min:999,   
      
      activation_fee: 0,
    },
    'No Vendor Promo': {
      pozative_Only_Monthly: 150,
      pozative_Only_Annually: 100,
      verifications_Only_Monthly:150,
      verifications_Only_Annually:100,
      aditCore_monthly:299,
      aditCore_annually:249,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:100, 
      activation_fee: 500,
    },
    'Inbound Core': {
      // techMonthly: 250,
      // techMonthly_Disc: 499,
      // techAnnual: 250,
      // techAnnual_Disc: 349,
      // analyticMonthly: 250,
      // analyticMonthly_Disc: 549,
      // analyticAnnual: 250,
      // analyticAnnual_Disc: 459,
      aditCore_monthly:299,
      aditCore_annually:249,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:150,
      activation_fee: 500,
      hardwareCreditAnnually: 500,
      hardwareCreditMonthly:300,
      hardwareCreditAditLiteAnnually: 250,
      // hardwareCreditAditLiteMonthly:0
    },
    'Inbound Free Verifications': {
      // techMonthly: 250,
      // techMonthly_Disc: 499,
      // techAnnual: 250,
      // techAnnual_Disc: 349,
      // analyticMonthly: 250,
      // analyticMonthly_Disc: 549,
      // analyticAnnual: 250,
      // analyticAnnual_Disc: 459,
      aditCore_monthly:349,
      aditCore_annually:299,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:100,
      activation_fee: 500,
    },
    'Outbound Core': {
      // techMonthly: 250,
      // techMonthly_Disc: 499,
      // techAnnual: 250,
      // techAnnual_Disc: 349,
      // analyticMonthly: 250,
      // analyticMonthly_Disc: 549,
      // analyticAnnual: 250,
      // analyticAnnual_Disc: 459,
      aditCore_monthly:299,
      aditCore_annually:249,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:150,
      activation_fee: 500,
      hardwareCreditAnnually: 500,
      hardwareCreditMonthly:500,
      hardwareCreditAditLiteAnnually: 250,
      hardwareCreditAditLiteMonthly:0
    },
    'Outbound Free Verifications': {
      // techMonthly: 250,
      // techMonthly_Disc: 499,
      // techAnnual: 250,
      // techAnnual_Disc: 349,
      // analyticMonthly: 250,
      // analyticMonthly_Disc: 549,
      // analyticAnnual: 250,
      // analyticAnnual_Disc: 459,
      aditCore_monthly:349,
      aditCore_annually:299,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:100,
      activation_fee: 500,
    },
    'Outbound Core - 1st Yr': {
      // techMonthly: 250,
      // techMonthly_Disc: 499,
      // techAnnual: 250,
      // techAnnual_Disc: 349,
      // analyticMonthly: 250,
      // analyticMonthly_Disc: 549,
      // analyticAnnual: 250,
      // analyticAnnual_Disc: 459,
      aditCore_monthly:349,
      aditCore_annually:299,
      add_on_phones:100,
      add_on_analytic:100,
      add_on_verification:150,
      activation_fee: 500,
      hardwareCreditAnnually: 500,
      hardwareCreditMonthly:500,
      hardwareCreditAditLiteAnnually: 250,
      hardwareCreditAditLiteMonthly:0
    },
    Reseller: {
      techMonthly: 599,
      techMonthly_Disc: 499,
      techAnnual: 549,
      techAnnual_Disc: 349,
      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticAnnual: 649,
      analyticAnnual_Disc: 459,
      activation_fee: 100,
      hardwareCreditAnnually: 750,
      hardwareCreditMonthly:300
    },
  };
