export const promotionPricing = {
    'Smile Source': {
      techMonthly: 599,
      techMonthly_Disc: 349,
      techAnnual: 549,
      techAnnual_Disc: 289,
      analyticMonthly: 699,
      analyticMonthly_Disc: 449,
      analyticAnnual: 649,
      analyticAnnual_Disc: 379,
      activation_fee: 0,
    },
    TruBlu: {
      techMonthly: 599,
      techMonthly_Disc: 499,
      techAnnual: 549,
      techAnnual_Disc: 349,
      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticAnnual: 649,
      analyticAnnual_Disc: 459,
      activation_fee: 0,
    },
    DDSOM: {
      techMonthly: 599,
      techMonthly_Disc: 499,
      techAnnual: 549,
      techAnnual_Disc: 349,
      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticAnnual: 649,
      analyticAnnual_Disc: 459,
      activation_fee: 0,
    },
    'AIDA Member': {
      techMonthly: 599,
      techMonthly_Disc: 499,
      techAnnual: 549,
      techAnnual_Disc: 349,
      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticAnnual: 649,
      analyticAnnual_Disc: 459,
      activation_fee: 0,
    },
    Custom: {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:349,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:299,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,

      activation_fee: 500,
    },
    Event: {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:349,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:299,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,

      activation_fee: 500,
    },
    'Outbound AE': {
      techMonthly: 599,
      techMonthly_Disc: 399,
      techMonthly_Disc_Min:349,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 349,
      techAnnual_Disc_Min:299,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 499,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 449,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,      
      activation_fee: 500,
    },
    'Outbound AE (Lite)': {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:249,
      techMonthly_Disc_Max:449,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:199,
      techAnnual_Disc_Max:399,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:549,
      analyticMonthly_Disc_Min:449,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:499,
      analyticAnnual_Disc_Min:399,   
      
      aditLiteMontly:499,
      aditLiteMontly_Disc: 349,
      aditLiteMontly_Disc_Max:349,
      aditLiteMontly_Disc_Min:249,   

      aditLiteAnnual:449,
      aditLiteAnnual_Disc: 299,
      aditLiteAnnual_Disc_Max:299,
      aditLiteAnnual_Disc_Min:199,   

      activation_fee: 500,
    },
    'Only Lite': {
      aditLiteMontly:499,
      aditLiteMontly_Disc: 349,
      aditLiteMontly_Disc_Max:349,
      aditLiteMontly_Disc_Min:249,   

      aditLiteAnnual:449,
      aditLiteAnnual_Disc: 299,
      aditLiteAnnual_Disc_Max:299,
      aditLiteAnnual_Disc_Min:199,   

      activation_fee: 500,
    },
    'Only Lite - 1st Yr Promo': {
      aditLiteMontly:499,
      aditLiteMontly_Disc: 349,
      aditLiteMontly_Disc_Max:349,
      aditLiteMontly_Disc_Min:249,   

      aditLiteAnnual:449,
      aditLiteAnnual_Disc: 299,
      aditLiteAnnual_Disc_Max:299,
      aditLiteAnnual_Disc_Min:199,   

      activation_fee: 500,
    },
    Admin: {
      techMonthly: 599,
      techMonthly_Disc: 449,
      techMonthly_Disc_Min:0,
      techMonthly_Disc_Max:999,

      techAnnual: 549,
      techAnnual_Disc: 399,
      techAnnual_Disc_Min:0,
      techAnnual_Disc_Max:999,

      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticMonthly_Disc_Max:0,
      analyticMonthly_Disc_Min:999,

      analyticAnnual: 649,
      analyticAnnual_Disc: 499,
      analyticAnnual_Disc_Max:0,
      analyticAnnual_Disc_Min:999,   
      
      activation_fee: 0,
    },
    'Inbound Core (New)': {
      techMonthly: 250,
      techMonthly_Disc: 499,
      techAnnual: 250,
      techAnnual_Disc: 349,
      analyticMonthly: 250,
      analyticMonthly_Disc: 549,
      analyticAnnual: 250,
      analyticAnnual_Disc: 459,
      activation_fee: 100,
    },
    'Outbound Core (New)': {
      techMonthly: 250,
      techMonthly_Disc: 499,
      techAnnual: 250,
      techAnnual_Disc: 349,
      analyticMonthly: 250,
      analyticMonthly_Disc: 549,
      analyticAnnual: 250,
      analyticAnnual_Disc: 459,
      activation_fee: 100,
    },
    'Outbound Core (New) - 1st Yr': {
      techMonthly: 250,
      techMonthly_Disc: 499,
      techAnnual: 250,
      techAnnual_Disc: 349,
      analyticMonthly: 250,
      analyticMonthly_Disc: 549,
      analyticAnnual: 250,
      analyticAnnual_Disc: 459,
      activation_fee: 100,
    },
    Reseller: {
      techMonthly: 599,
      techMonthly_Disc: 499,
      techAnnual: 549,
      techAnnual_Disc: 349,
      analyticMonthly: 699,
      analyticMonthly_Disc: 549,
      analyticAnnual: 649,
      analyticAnnual_Disc: 459,
      activation_fee: 100,
    },
  };
